language: python
python:
  - "3.6"
services:
  -postgresql

install:
  - "pip install pytest"
  - "pip install -r requirements.txt"
  - "pip install coveralls"

env:
  TEST_DATABASE="postgresql://postgres:''@127.0.0.1/test_stackoverflow"
  DATABASE="postgresql://postgres:''@127.0.0.1/stackoverflow"
  CONFIG=testing

before_script:
  - psql -c 'create database stackoverflow;' -U postgres
  - psql -c 'create database test_stackoverflow;' -U postgres

script: pytest --cov=app

after_success:
- coveralls 


