language: python

python:
  - "3.6.5"
  - "nightly" # latest version of python that is publicly available
install:

  - "pip install -r requirements.txt"
  - "pip install coveralls"

script:
  - py.test --cov=app

 after_success:
- coveralls 